JSON formatting changed to YAML in first_steps tutorial
At least for cookiecutter 1.6.0, json style config files are not supported. The poyo parser does not recognise JSON files and will throw the following error if you try and use the JSON file that the tutorial advises:

```
NoMatchException: None of the known patterns match for {
    "directory_name": "Hello",
    "file_name": "Howdy",
    "greeting_recipient": "Julie"
}
```
This simple patch just changes the JSON style config file to YAML (but keeps the json extension)